#!/usr/bin/perl
my $APP = 'pickyfont';
my $VERSION = 0.4;
# pickyfont - Pick Your Font... on the fly
# Copyright (C) 2010 Magnus Woldrich <trapd00r@trapd00r.se>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use Data::Dumper;
use Picky::Fonts qw(getfonts setfont);

my ($action, $font, $typeface) = @ARGV;
$typeface = 'all' unless $typeface; # set normal,bold,italic to same font

my $opts = {
  list      => sub {getfonts();},
  set       => sub {setfont($font, $typeface); exit 0;},
  help      => sub {usage(); exit 0},
  '--help'  => sub {usage(); exit 0},
};

# Due to how setfont() works, this is really not necessary
# If the font provided to getfont() isnt defined, it'll be evaluated as
# a arbitary font.
# If the font is invalid, nothing will happen
if($action eq 'arb') {
  chomp($font);
  $opts->{set}->();
  exit 0;
}


# Hereby the 'set' argument isn't necessary
# setfont() will return if it's not a legal font
if(defined($action)) {
  if($action !~ /^(:?list|set|.?.?help)$/) {
    setfont($action, $font);
  }
}

$opts->{help}->() if !$action;

defined $opts->{$action} && $opts->{$action}->();

sub usage {
  print << "USAGE";
  $APP $VERSION
  USAGE: $APP OPTIONS

  OPTIONS
    list  list available fonts
    set   font (typeface)
    arb   set font to arbitary string, see below

    Typeface can be normal, bold, italic or all

    You can specify arbitary font to use, like so:
      pickyfont arb lucidasanstypewriter-bold-24
    The 'arb' flag is optional:
      pickyfont 8x13
    is valid as well
USAGE
  exit 0;
}
