#!/usr/bin/perl
use strict;
use vars qw($VERSION);
my $APP  = 'pickyfont';
$VERSION = '0.470';

use lib 'lib';

use Picky::Fonts qw(getfonts setfont);
use Pod::Usage;

my ($action, $font, $typeface) = @ARGV;
$typeface = 'all' unless $typeface; # set normal,bold,italic to same font

my $opts = {
  list      => sub { getfonts(); },
  set       => sub { setfont($font, $typeface) and exit 0; },
  help      => sub { pod2usage(verbose=>1); },
  man       => sub { pod2usage(verbose=>3); },
};

# Due to how setfont() works, this is really not necessary
# If the font provided to getfont() isnt defined, it'll be evaluated as
# a arbitary font.
# If the font is invalid, nothing will happen
if($action eq 'arb') {
  chomp($font);
  $opts->{set}->();
  exit 0;
}

# Hereby the 'set' argument isn't necessary
# setfont() will return if it's not a legal font
if(defined($action)) {
  if($action !~ /^(:?list|set|[-]*help)$/) {
    setfont($action, $font);
  }
}

$opts->{help}->() if !$action;

defined $opts->{$action} && $opts->{$action}->();

sub usage { pod2usage(verbose=>1) }

=pod

=head1 NAME

pickyfont - Change terminal font on the fly

=head1 DESCRIPTION

pickyfont lets you change your X-terminal font on the fly, just like setfont
can do in a TTY.

Normal, bold and italic fontfaces are supported, as well as XFT fonts.

Since the italic face does not look good in a terminal, you could use a
different font that will be used when the terminal wants to print data in
italic.

There are some very good fonts that sadly does not provide a boldface, and you
can solve this problem by simply doing the same thing here.

The author highly recommends 'monte1' for normal text, 'monte2' for bold and
'pro1' for italic. Looks really good.

Another use is when you want to show some data to a couple of friends standing
around your computer, or have the music playlist open,  they'll most likely
not see anything at all since you are using a small font suitable for one
pair of eyes only.

Simply do <pickyfont ter7> and you can lay back in the sofa chillin'.

=head1

=head1 OPTIONS

  set     set font, and optionally, typeface
  list    list available fonts
  arb     set font to an arbitary string
  help    show help and exit
  man     show the manual

=head2 Typeface

Typeface, or attribute, is one of normal, bold, italic, or simply 'all'.

=head3 Examples

This is what the author prefers.

  pickyfont set monte1 normal
  pickyfont set monte2 bold
  pickyfont set pro1   italic

=head2  Arbitary fonts

  You can specifiy arbitary fonts using the following syntax:

  pickyfont lucidasanstypewriter-bold-24
  pickyfont 8x13

=head1 CAVEATS

There is no reliable way to get friendly font names from the X.org server.
One could parse the output from xlsfonts, but that output could be insanely long
and will only show the raw names and several duplicates as well.

Therefore I see no other way than to keeping a (configuration)? file with more
or less standard font mappings that most people would (in many cases, should)
have installed, and let them pick from that.

Please send me an e-mail if there's a better way of doing this.

=head1 FONT RECOMMENDATIONS

The Terminus font is excellent, comes with a pcf version for the TTY and several
sizes. The smallest pixelsize available is 12pt, which is a bit to big for me
though, and there's no boldface unless you pump the size up to 14.

The Profont font is excellent as well, and when you're used to it, it's even
more readable. No boldface here at all.

The Monte Carlo font is awesome. It comes with just one size, but there's a bold
version that works really well. This is what the author uses everyday.

Other than that, there are some more or less good programming fonts in the
artwiz packages that you might like more.

There's also only one font that supports all of codepage 437 - The Lucida
Console Pro. Not recommended for coding, though.

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  magnus@trapd00r.se
  http://japh.se

=head1 REPORTING BUGS

L<magnus@trapd00r.se>

L<http://github.com/trapd00r/pickyfont/issues>

pickyfont homepage: L<http://github.com/trapd00r/pickyfont>

=head1 COPYRIGHT

Copyright (C) 2010, 2011 Magnus Woldrich. All right reserved.
This program is free software; you can redistribute it and/or modify it under
the same terms as Perl itself.

=head1 SEE ALSO

L<xlsfonts(1)>

=cut
